#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := am3202_test

EXTRA_COMPONENT_DIRS += src $(abspath ../mycomponents)

include $(IDF_PATH)/make/project.mk
